export const GET_JOBS = "GET_JOBS";
export const ADD_JOB = "ADD_JOB";
export const DELETE_JOB = "DELETE_JOB";
export const APPLY_JOB = "APPLY_JOB";

export const GET_ERRORS = "GET_ERRORS";
export const AUTH_ERROR = "AUTH_ERROR";
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_USERTYPE = "REGISTER_USERTYPE";
export const REGISTER_USERTYPE_ERROR = "REGISTER_USERTYPE_ERROR";
export const USER_TYPE_LOADING = "USER_TYPE_LOADING";
export const USER_TYPE_LOADED = "USER_TYPE_LOADED";
export const USER_TYPE_LOADING_ERROR = "USER_TYPE_LOADING_ERROR";

export const UPLOAD_APPLICATION = "UPLOAD_APPLICATION";
export const UPLOAD_APPLICATION_ERROR = "UPLOAD_APPLICATION_ERROR";




